apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cmproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmproxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
