apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmproxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cmproxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
