apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: default
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: custom-metrics-stackdriver-adapter
      k8s-app: custom-metrics-stackdriver-adapter
  template:
    metadata:
      labels:
        run: custom-metrics-stackdriver-adapter
        k8s-app: custom-metrics-stackdriver-adapter
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google-containers/custom-metrics-stackdriver-adapter:v0.1.0
          imagePullPolicy: Always
          name: pod-custom-metrics-stackdriver-adapter
          command:
            - /adapter
            - --requestheader-client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 250m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Adapter
  name: custom-metrics-stackdriver-adapter
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: custom-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiVersion: v1
  kind: ServiceAccount
  name: custom-metrics-stackdriver-adapter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: custom-metrics-auth-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-metrics-authentication-reader
subjects:
- apiVersion: v1
  kind: ServiceAccount
  name: custom-metrics-stackdriver-adapter
  namespace: default
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom-metrics.metrics.k8s.io
  groupPriorityMinimum: 100
  versionPriority: 100
  priority: 100
  service:
    name: custom-metrics-stackdriver-adapter
    namespace: default
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: custom-metrics-reader
rules:
- apiGroups:
  - "custom-metrics.metrics.k8s.io"
  resources:
  - "*"
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: all-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-reader
subjects:
- apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: Group
  name: system:anonymous
- apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: Group
  name: system:unauthenticated
