apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: custom-metrics-stackdriver-adapter
      k8s-app: custom-metrics-stackdriver-adapter
  template:
    metadata:
      labels:
        run: custom-metrics-stackdriver-adapter
        k8s-app: custom-metrics-stackdriver-adapter
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: custom-metrics-stackdriver-adapter
      containers:
      - image: "gcr.io/google-containers/custom-metrics-stackdriver-adapter:v0.8.0"
        imagePullPolicy: Always
        name: pod-custom-metrics-stackdriver-adapter
        command:
        - /adapter
        - --use-new-resource-model=false
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp-service-account.json
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 200Mi
        volumeMounts:
        - mountPath: /secrets
          name: secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: custom-metrics-stackdriver-adapter
          items:
          - key: key.json
            path: gcp-service-account.json
