apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsub-publisher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pubsub-publisher
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-publisher-key
      containers:
      - name: publisher
        image: gcr.io/aleksandram-public-images/pubsub_publisher:dev
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        command:
          - ./pubsub_publisher
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: GOOGLE_CLOUD_PROJECT
          value: aleksandram-gke-dev
        - name: TOPIC
          value: test-topic
        - name: INTERVAL
          value: 1s
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
